# Source: https://swagger.io/docs/specification/v3_0/basic-structure/
openapi: 3.0.0
info:
  title: Kennzahlen-Cockpit-API
  version: 1.0.0
tags:
  - name: Kennzahlen
    description: Endpunkte für das Abrufen von aktuellen und historischen Kennzahl-Werten
  - name: Custom-Kennzahlen
    description: Endpunkte für das erstellen, bearbeiten und abrufen von Custom-Kennzahlen
paths:
  /api/keyFigures/current/:id:
    get:
      tags:
        - Kennzahlen
      summary: Aktuelle Werte
      parameters:
        - name: id
          description: ID des Unternehmens
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: Aktuelle Kennzahlen der gesuchten Unternehmung
          content: # Response body
            application/json: # Media type
              schema: # Must-have
                type: object # Data type
                properties:
                  period:
                    type: integer
                  keyFigures:
                    type: object
                example: # Sample data
                  period: 2025
                  keyFigures:
                    equityRatio: 0.1
                    debtRatio: 0.3296296296296296
                    selfFinancingRatio: 0.9567567567567568
                    workingCapitalIntensity: 0.8962962962962963
                    fixedAssetIntensity: 0.1037037037037037
                    cashRatio: 2.151898734177215
                    quickCash: 3.0253164556962027
                    currentRatio: 6.1265822784810124
                    fixedAssetCoverage1: 3.3035714285714284
                    fixedAssetCoverage2: 5.071428571428571
                    roe: 0.7081081081081081
                    roa: 0.24444444444444444
                    profitMargin: 0.4337748344370861
        404:
          description: Keine Abschlussberichte gefunden
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: no reports were found for company [name]

  /api/keyFigures/historic/:id:
    get:
      tags:
        - Kennzahlen
      summary: Historische Werte
      parameters:
        - name: id
          description: ID des Unternehmens
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: Historische Kennzahlen der gesuchten Unternehmung
          content:
            application/json:
              schema:
                type: object
                properties:
                  equityRatio:
                    type: array
                    items:
                      type: object
                      properties:
                        period:
                          type: integer
                        key_figure:
                          type: number
                  debtRatio:
                    type: array
                    items:
                      type: object
                      properties:
                        period:
                          type: integer
                        key_figure:
                          type: number
                  selfFinancingRatio:
                    type: array
                    items:
                      type: object
                      properties:
                        period:
                          type: integer
                        key_figure:
                          type: number
                  workingCapitalIntensity:
                    type: array
                    items:
                      type: object
                      properties:
                        period:
                          type: integer
                        key_figure:
                          type: number
                  fixedAssetIntensity:
                    type: array
                    items:
                      type: object
                      properties:
                        period:
                          type: integer
                        key_figure:
                          type: number
                  cashRatio:
                    type: array
                    items:
                      type: object
                      properties:
                        period:
                          type: integer
                        key_figure:
                          type: number
                  quickCash:
                    type: array
                    items:
                      type: object
                      properties:
                        period:
                          type: integer
                        key_figure:
                          type: number
                  currentRatio:
                    type: array
                    items:
                      type: object
                      properties:
                        period:
                          type: integer
                        key_figure:
                          type: number
                  fixedAssetCoverage1:
                    type: array
                    items:
                      type: object
                      properties:
                        period:
                          type: integer
                        key_figure:
                          type: number
                  fixedAssetCoverage2:
                    type: array
                    items:
                      type: object
                      properties:
                        period:
                          type: integer
                        key_figure:
                          type: number
                  roe:
                    type: array
                    items:
                      type: object
                      properties:
                        period:
                          type: integer
                        key_figure:
                          type: number
                  roa:
                    type: array
                    items:
                      type: object
                      properties:
                        period:
                          type: integer
                        key_figure:
                          type: number
                  profitMargin:
                    type: array
                    items:
                      type: object
                      properties:
                        period:
                          type: integer
                        key_figure:
                          type: number
                example:
                  # Example response generated by ChatGPT
                  # Source: https://chatgpt.com/share/680cd84d-5918-8011-90d4-3a334a87d3c8
                  equityRatio:
                    - period: 2024
                      key_figure: 0.43272727272727274
                    - period: 2023
                      key_figure: 0.3933649289099526
                    - period: 2022
                      key_figure: 0.44
                  debtRatio:
                    - period: 2024
                      key_figure: 0.5672727272727273
                    - period: 2023
                      key_figure: 0.6066350710900474
                    - period: 2022
                      key_figure: 0.56
                  selfFinancingRatio:
                    - period: 2024
                      key_figure: 0.36
                    - period: 2023
                      key_figure: 0.18571428571428572
                    - period: 2022
                      key_figure: 0.17857142857142858
                  workingCapitalIntensity:
                    - period: 2024
                      key_figure: 0.27045454545454545
                    - period: 2023
                      key_figure: 0.35545023696682465
                    - period: 2022
                      key_figure: 0.27466666666666667
                  fixedAssetIntensity:
                    - period: 2024
                      key_figure: 0.7295454545454545
                    - period: 2023
                      key_figure: 0.6445497630331753
                    - period: 2022
                      key_figure: 0.7253333333333334
                  cashRatio:
                    - period: 2024
                      key_figure: 0.20114942528735633
                    - period: 2023
                      key_figure: 0.30303030303030304
                    - period: 2022
                      key_figure: 0.175
                  quickCash:
                    - period: 2024
                      key_figure: 1.0632183908045978
                    - period: 2023
                      key_figure: 1.5151515151515151
                    - period: 2022
                      key_figure: 1.425
                  currentRatio:
                    - period: 2024
                      key_figure: 1.7097701149425288
                    - period: 2023
                      key_figure: 2.272727272727273
                    - period: 2022
                      key_figure: 2.575
                  fixedAssetCoverage1:
                    - period: 2024
                      key_figure: 0.43613707165109034
                    - period: 2023
                      key_figure: 0.5147058823529411
                    - period: 2022
                      key_figure: 0.5147058823529411
                  fixedAssetCoverage2:
                    - period: 2024
                      key_figure: 0.9968847352024922
                    - period: 2023
                      key_figure: 1.213235294117647
                    - period: 2022
                      key_figure: 1.1397058823529411
                  roe:
                    - period: 2024
                      key_figure: 0.31142857142857144
                    - period: 2023
                      key_figure: 1.0857142857142856
                    - period: 2022
                      key_figure: 0.014285714285714285
                  roa:
                    - period: 2024
                      key_figure: 0.12590909090909091
                    - period: 2023
                      key_figure: 0.3744075829383886
                    - period: 2022
                      key_figure: 0.048
                  profitMargin:
                    - period: 2024
                      key_figure: 0.04839067702552719
                    - period: 2023
                      key_figure: 0.1688888888888889
                    - period: 2022
                      key_figure: 0.002197802197802198
                  Custom-Kennzahl-1:
                    - period: 2024
                      key_figure: 280
                    - period: 2023
                      key_figure: 250
                    - period: 2022
                      key_figure: 335
                  Custom-Kennzahl-2:
                      - period: 2024
                        key_figure: 0.37815126050420167
                      - period: 2023
                        key_figure: 0.3333333333333333
                      - period: 2022
                        key_figure: 0.44660194174757284
        404:
          description: Keine Abschlussberichte gefunden
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: no reports were found for company [name]
  /api/customKeyFigures:
    get:
      tags:
        - Custom-Kennzahlen
      summary: Alle gespeicherten Custom-Kennzahlen
      responses:
        200:
          description:
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                    name:
                      type: string
                    formula:
                      type: string
                    type:
                      type: string
                      enum:
                        - numeric
                        - percentage
                    __v:
                      type: integer
                      example: 0
              example:
                - _id: "6807759eb81cadc3ac9893d2"
                  name: "Cashflow"
                  formula: "liquid_assets+depreciation"
                  type: "numeric"
                  __v: 0
                - _id: "680b838372e7191c1b28a474"
                  name: "Vorratsanteil"
                  formula: "stocks/current_assets"
                  type: "percentage"
                  __v: 0