openapi: 3.0.0
info:
  title: Kennzahlen-Cockpit-API
  version: 1.0.0
paths:
  /api/companies:
    get:
      summary: Get all companies
      responses:
        "200":
          description: An array with all companies

